benches/mod.rs
src/templates/mod.rs
src/templates/repl.rs

So this is a super low-quality message replacement implementation to see what kinds of approaches can be taken.
The issue I have is that Elasticsearch isn't 'aware' of the message template, so can't do what Seq does and construct a message from a template and parameters.
To get around this, I've added a method called `replace` on `MessageTemplate`. To support this, when parsing the template I'm building up a list of slices, so the replaced String can be built nice and efficiently.
The main issue I think is the parsing is a mess of different approaches and introduces a bunch of ways to create errors. This could be cleaned up and the replacement methods refactored / DRYed.
What do you think?

Initial Template replacement

---

src/collectors/mod.rs
src/collectors/seq/mod.rs
src/collectors/stdio/mod.rs
src/enrichers/fixed_property/mod.rs
src/events.rs
src/pipeline/ambient.rs
src/pipeline/async.rs
src/pipeline/chain.rs
src/pipeline/reference.rs

First step for #12. While `Event` is now generic in `'a`, usages thoughout the library specify the concrete `'static` bound.
Next step is to parameterize the pipeline itself.

Parameterize Event with the lifetime bound of its property names

---

src/formatters/json/mod.rs
src/formatters/raw/mod.rs

Millisecond timestamp precision in JSON format, 9-place (nanosecond) precision in raw.

Fractional timestamp precision

---

src/collectors/seq/mod.rs
src/enrichers/fixed_property/mod.rs
src/events.rs
src/formatters/json/mod.rs
src/formatters/raw/mod.rs
src/lib.rs
src/pipeline/builder.rs
src/templates/repl.rs
src/test_support.rs

Fixes #23. Further, removes spurious quotes from the plain text formatted messages.

Introduce events::Value to distinguish between raw string, JSON, and values

---

Cargo.toml
README.md
src/collectors/mod.rs
src/enrichers/fixed_property/mod.rs
src/events.rs
src/formatters/json/mod.rs
src/lib.rs
src/pipeline/ambient.rs
src/pipeline/async.rs
src/pipeline/builder.rs
src/pipeline/reference.rs
src/test_support.rs

Part of #29.
I'm keen to rename `eminfo` -> `info` etc. as part of this ticket - thoughts?

Breaks the dependency on `log`

---

src/events.rs
src/formatters/json/mod.rs
src/lib.rs
src/templates/mod.rs

Implements the "rendered" variant of the JSON format specified in: https://github.com/serilog/serilog-formatting-compact

Alternative, rendered, JSON formatting implementation

---

Cargo.toml
README.md
batcher/Cargo.toml
batcher/README.md
core/Cargo.toml
emitter/file/Cargo.toml
emitter/file/README.md
emitter/file/src/lib.rs
emitter/opentelemetry/Cargo.toml
emitter/opentelemetry/README.md
emitter/opentelemetry/src/lib.rs
emitter/otlp/Cargo.toml
emitter/otlp/README.md
emitter/otlp/gen/Cargo.toml
emitter/otlp/src/lib.rs
emitter/term/Cargo.toml
emitter/term/README.md
emitter/term/src/lib.rs
examples/common_patterns/Cargo.toml
examples/opentelemetry/direct_otlp/Cargo.toml
examples/opentelemetry/via_sdk/Cargo.toml
macros/Cargo.toml
macros/README.md
src/lib.rs
src/setup.rs

From this release onwards, I'll track changes properly. I've moved the source from my playground repository and updated links since `0.11.0-alpha.2`.

Prepare for 0.11.0-alpha.3 release

---

emitter/term/src/lib.rs
examples/common_patterns/Cargo.toml
examples/common_patterns/span_auto_result_completion.rs
examples/common_patterns/span_manual.rs
macros/src/args.rs
macros/src/emit.rs
macros/src/lib.rs
macros/src/span.rs
src/macro_hooks.rs
src/span.rs

Closes #48 
This PR introduces the `ok_lvl` and `err_lvl` control parameters that can complete spans instrumenting fallible functions:
```rust
#[emit::span(
ok_lvl: emit::Level::Info,
err_lvl: emit::Level::Error,
"Running an example",
i,
)]
fn example(i: i32) -> Result<(), Error> {
let r = i + 1;
if r == 4 {
Err(Error { n: r })
} else {
Ok(())
}
}
```

Support completing spans as results

---

core/src/template.rs
emitter/otlp/src/client.rs
emitter/otlp/src/lib.rs
examples/common_patterns/span_manual.rs
examples/common_patterns/span_manual_completion.rs
examples/common_patterns/span_trace_propagation.rs
macros/src/emit.rs
macros/src/event.rs
macros/src/lib.rs
macros/src/span.rs
src/metric.rs
src/span.rs

This cleans up the default template formatting so it looks like a valid `format_args!` by default. I've also renamed the `event` control parameter to `evt`, to better fit the compact naming scheme of other parameters.

Default Template formatting to braced and rename event to evt

---

core/src/path.rs
emitter/file/src/lib.rs
emitter/opentelemetry/src/lib.rs

The `emit_opentelemetry` docs were mostly just wrong so I've updated them and removed any lingering API artifacts from its old approach.

Clean up emit_opentelemetry API and add troubleshooting docs

---

Cargo.toml
README.md
batcher/Cargo.toml
batcher/README.md
core/Cargo.toml
emitter/file/Cargo.toml
emitter/file/README.md
emitter/file/src/lib.rs
emitter/opentelemetry/Cargo.toml
emitter/opentelemetry/README.md
emitter/opentelemetry/src/lib.rs
emitter/otlp/Cargo.toml
emitter/otlp/README.md
emitter/otlp/gen/Cargo.toml
emitter/otlp/src/lib.rs
emitter/term/Cargo.toml
emitter/term/README.md
emitter/term/src/lib.rs
examples/common_patterns/Cargo.toml
examples/opentelemetry/direct_otlp/Cargo.toml
examples/opentelemetry/via_sdk/Cargo.toml
macros/Cargo.toml
macros/README.md
src/lib.rs
src/setup.rs

* fix a typo in the readme by @KodrAus in https://github.com/emit-rs/emit/pull/56
* Split otlp channels so they don't block eachother by @KodrAus in https://github.com/emit-rs/emit/pull/60
* Include event module in default file writer by @KodrAus in https://github.com/emit-rs/emit/pull/61
* Clean up emit_opentelemetry API and add troubleshooting docs by @KodrAus in https://github.com/emit-rs/emit/pull/62

Prepare for 0.11.0-alpha.6 release

---

Cargo.toml
README.md
batcher/Cargo.toml
batcher/README.md
core/Cargo.toml
emitter/file/Cargo.toml
emitter/file/README.md
emitter/file/src/lib.rs
emitter/opentelemetry/Cargo.toml
emitter/opentelemetry/README.md
emitter/opentelemetry/src/lib.rs
emitter/otlp/Cargo.toml
emitter/otlp/README.md
emitter/otlp/gen/Cargo.toml
emitter/otlp/src/lib.rs
emitter/term/Cargo.toml
emitter/term/README.md
emitter/term/src/lib.rs
examples/common_patterns/Cargo.toml
examples/opentelemetry/direct_otlp/Cargo.toml
examples/opentelemetry/via_sdk/Cargo.toml
macros/Cargo.toml
macros/README.md
src/lib.rs
src/setup.rs

* Use diagnostic::on_unimplemented to improve error messages from emit::as_* attributes by @KodrAus in https://github.com/emit-rs/emit/pull/64
* Fill in tests for core by @KodrAus in https://github.com/emit-rs/emit/pull/65
This release contains the following breaking changes:
- `Path::new` is no longer `const` and now returns a `Result`. It will only return `Ok` for valid paths. The original method has been renamed to `Path::new_unchecked`, which doesn't parse the path. It is otherwise still a safe API.

Prepare for 0.11.0-alpha.7 release

---

Cargo.toml
core/src/extent.rs
core/src/value.rs
src/frame.rs
src/kind.rs
src/level.rs
src/span.rs

This PR continues adding tests for functionality, this time around the `Kind` and `Level` types and their various filters. I found some issues with the existing `MinLevelPathMap` type so have reworked it.

Test filters on kinds and levels

---

Cargo.toml
README.md
batcher/Cargo.toml
batcher/README.md
core/Cargo.toml
emitter/file/Cargo.toml
emitter/file/README.md
emitter/file/src/lib.rs
emitter/opentelemetry/Cargo.toml
emitter/opentelemetry/README.md
emitter/opentelemetry/src/lib.rs
emitter/otlp/Cargo.toml
emitter/otlp/README.md
emitter/otlp/gen/Cargo.toml
emitter/otlp/src/lib.rs
emitter/term/Cargo.toml
emitter/term/README.md
emitter/term/src/lib.rs
examples/common_patterns/Cargo.toml
examples/opentelemetry/direct_otlp/Cargo.toml
examples/opentelemetry/via_sdk/Cargo.toml
macros/Cargo.toml
macros/README.md
src/lib.rs
src/setup.rs

- The ordering of `Event::new` arguments has changed. The most stable arguments (those that identify the callsite) are first, and the least stable (those that change between instances) are last. The order is now module, template, extent, props.
- `module` has been renamed to `mdl` to match the shortened convention used by other fields like `tpl` for template.
- The precedence of properties has been fixed in many contexts so the most local data is always preferred over the most ambient.
* Add tests for `emit` APIs by @KodrAus in https://github.com/emit-rs/emit/pull/69
* Test filters on kinds and levels by @KodrAus in https://github.com/emit-rs/emit/pull/70
* Add integration tests for macros by @KodrAus in https://github.com/emit-rs/emit/pull/71

Prepare for 0.11.0-alpha.8 release

---

Cargo.toml
README.md
batcher/Cargo.toml
batcher/README.md
core/Cargo.toml
emitter/file/Cargo.toml
emitter/file/README.md
emitter/file/src/lib.rs
emitter/opentelemetry/Cargo.toml
emitter/opentelemetry/README.md
emitter/opentelemetry/src/lib.rs
emitter/otlp/Cargo.toml
emitter/otlp/README.md
emitter/otlp/gen/Cargo.toml
emitter/otlp/src/lib.rs
emitter/term/Cargo.toml
emitter/term/README.md
emitter/term/src/lib.rs
examples/common_patterns/Cargo.toml
examples/opentelemetry/direct_otlp/Cargo.toml
examples/opentelemetry/via_sdk/Cargo.toml
macros/Cargo.toml
macros/README.md
src/lib.rs
src/setup.rs

- The `emit::event!` macro has been renamed to `emit::evt!` to fit the shorter naming scheme used for `tpl!`, `props!`, etc.
- The `Init` type now carries a lifetime parameter instead of references to its arguments.
* Stub out UI fail tests by @KodrAus in https://github.com/emit-rs/emit/pull/75
* Add integration tests for OTLP by @KodrAus in https://github.com/emit-rs/emit/pull/76

Prepare for 0.11.0-alpha.9 release

---

.github/workflows/otlp.yml
Cargo.toml
core/src/timestamp.rs
emitter/otlp/src/client.rs
emitter/otlp/test/throughput/Cargo.toml
emitter/otlp/test/throughput/config.yaml
emitter/otlp/test/throughput/src/main.rs
src/metric.rs

This PR adds another integration-like test for the OTLP emitter. This one writes 10,000 events as quickly as possible through the collector and emits some stats about how it went. It should give us a reasonable basis to investigate optimization opportunities from in the future.

Add a test project for OTLP emitter throughput

---

batcher/src/internal_metrics.rs
batcher/src/lib.rs
batcher/src/sync.rs
batcher/src/tokio.rs
emitter/file/src/lib.rs
emitter/otlp/src/client.rs
emitter/otlp/src/lib.rs

Closes #68 
The default background batching implementation will truncate all unprocessed events if it fills up. This is to prevent logging from blocking up the works, and based on the assumption that newer events are more important than older ones.
This isn't suitable for using the batcher for auditing or proxying use-cases so this PR introduces a function that emitters can use to block waiting for the current batch to be flushed if it's full instead of truncating. If this times out instead of adding the event then it's returned to the caller, who can then discard it or issue a destructive non-blocking send instead.

Allow batcher to block on a full queue instead of truncating

---

Cargo.toml
README.md
batcher/Cargo.toml
batcher/README.md
core/Cargo.toml
emitter/file/Cargo.toml
emitter/file/README.md
emitter/file/src/lib.rs
emitter/opentelemetry/Cargo.toml
emitter/opentelemetry/README.md
emitter/opentelemetry/src/lib.rs
emitter/otlp/Cargo.toml
emitter/otlp/README.md
emitter/otlp/src/lib.rs
emitter/term/Cargo.toml
emitter/term/README.md
emitter/term/src/lib.rs
examples/common_patterns/Cargo.toml
examples/opentelemetry/direct_otlp/Cargo.toml
examples/opentelemetry/via_sdk/Cargo.toml
macros/Cargo.toml
macros/README.md
src/lib.rs
src/setup.rs

- The `emit_batcher` API has been rewritten so it's clear where the distinction between `tokio` and `std` implementations is.
- `emit_otlp` will always spawn on a background thread, never on an existing `tokio` runtime.
* Add a test project for OTLP emitter throughput by @KodrAus in https://github.com/emit-rs/emit/pull/78
* Allow batcher to block on a full queue instead of truncating by @KodrAus in https://github.com/emit-rs/emit/pull/80

prepare for 0.11.0-alpha.10 release

---

batcher/Cargo.toml
batcher/src/lib.rs
batcher/src/sync.rs
batcher/src/tokio.rs

This PR continues to clean up `emit_batcher`, by making `tokio` versions async, with blocking variants using those, or the blocking variants in `sync`.

Add async variants of blocking tokio functions

---

Cargo.toml
README.md
batcher/Cargo.toml
batcher/README.md
core/Cargo.toml
emitter/file/Cargo.toml
emitter/file/README.md
emitter/file/src/lib.rs
emitter/opentelemetry/Cargo.toml
emitter/opentelemetry/README.md
emitter/opentelemetry/src/lib.rs
emitter/otlp/Cargo.toml
emitter/otlp/README.md
emitter/otlp/src/lib.rs
emitter/term/Cargo.toml
emitter/term/README.md
emitter/term/src/lib.rs
examples/common_patterns/Cargo.toml
examples/opentelemetry/direct_otlp/Cargo.toml
examples/opentelemetry/via_sdk/Cargo.toml
macros/Cargo.toml
macros/README.md
src/lib.rs
src/setup.rs

* Fix up explicit return breaking ok_lvl and err_lvl in sync spans by @KodrAus in https://github.com/emit-rs/emit/pull/85

Prepare for 0.11.0-alpha.12 release

---

core/src/emitter.rs
core/src/filter.rs
emitter/otlp/src/data.rs
emitter/otlp/src/data/logs.rs
emitter/otlp/src/data/logs/log_record.rs
emitter/otlp/src/data/resource.rs
emitter/otlp/src/data/traces/span.rs
examples/common_patterns/filter_per_emitter.rs

This PR generalizes the pattern we were using for wrapping emitters in filters with a new wrapping API. It lets you wrap emitters in middleware that can transform and filter along the way.

Emitter wrapping

---

Cargo.toml
README.md
batcher/Cargo.toml
batcher/README.md
core/Cargo.toml
emitter/file/Cargo.toml
emitter/file/README.md
emitter/file/src/lib.rs
emitter/opentelemetry/Cargo.toml
emitter/opentelemetry/README.md
emitter/opentelemetry/src/lib.rs
emitter/otlp/Cargo.toml
emitter/otlp/README.md
emitter/otlp/src/lib.rs
emitter/term/Cargo.toml
emitter/term/README.md
emitter/term/src/lib.rs
examples/common_patterns/Cargo.toml
examples/opentelemetry/direct_otlp/Cargo.toml
examples/opentelemetry/via_sdk/Cargo.toml
macros/Cargo.toml
macros/README.md
src/lib.rs
src/setup.rs

- Introduced a new `emit::emitter::wrapping` API for wrapping emitters in middleware for transformation and filtering.
- Make `err` properties in `emit_otlp` map to `exception.message`.
* Fix up flaky batcher test by @KodrAus in https://github.com/emit-rs/emit/pull/89
* Emitter wrapping by @KodrAus in https://github.com/emit-rs/emit/pull/90

Prepare for 0.11.0-alpha.13 release

---

.github/workflows/otlp.yml
batcher/src/tokio.rs
emitter/opentelemetry/Cargo.toml
emitter/opentelemetry/src/lib.rs
emitter/otlp/Cargo.toml
emitter/otlp/src/client/http.rs
emitter/otlp/test/integration/Cargo.toml
emitter/otlp/test/integration/config.tls.yaml
emitter/otlp/test/integration/src/main.rs
examples/opentelemetry/via_sdk/Cargo.toml
examples/opentelemetry/via_sdk/src/main.rs
macros/src/emit.rs
macros/src/span.rs

This PR updates `emit_openetelemetry` to the current versions of the `opentelemetry` crates. While I'm doing this I'll fill in tests for this side of the project.

Update openetelemetry crates to 0.24

---

batcher/src/lib.rs
core/src/emitter.rs
core/src/timestamp.rs
emitter/file/src/lib.rs
emitter/otlp/src/client.rs
emitter/term/src/lib.rs
src/kind.rs
src/level.rs

This PR includes some module info in the terminal output to make it a bit easier to tell what components are generating what logs.

Tweak the term format a touch to include some module info

---

Cargo.toml
README.md
batcher/Cargo.toml
batcher/README.md
core/Cargo.toml
emitter/file/Cargo.toml
emitter/file/README.md
emitter/file/src/lib.rs
emitter/opentelemetry/Cargo.toml
emitter/opentelemetry/README.md
emitter/opentelemetry/src/lib.rs
emitter/otlp/Cargo.toml
emitter/otlp/README.md
emitter/otlp/src/lib.rs
emitter/term/Cargo.toml
emitter/term/README.md
emitter/term/src/lib.rs
examples/common_patterns/Cargo.toml
examples/opentelemetry/direct_otlp/Cargo.toml
examples/opentelemetry/via_sdk/Cargo.toml
macros/Cargo.toml
macros/README.md
src/lib.rs
src/setup.rs

- `emit_file` and `emit_otlp` emitter spawning is now infallible. If spawning fails then they'll produce metrics and emit diagnostics to the internal logger.
* Add some more compile fail tests by @KodrAus in https://github.com/emit-rs/emit/pull/92
* Update openetelemetry crates to 0.24 by @KodrAus in https://github.com/emit-rs/emit/pull/93
* Add tests for emit_file by @KodrAus in https://github.com/emit-rs/emit/pull/95
* Bump dependencies by @KodrAus in https://github.com/emit-rs/emit/pull/100
* Add some tests for emit_term by @KodrAus in https://github.com/emit-rs/emit/pull/101
* Some docs and cleanups by @KodrAus in https://github.com/emit-rs/emit/pull/102
* Test re-opening existing log dirs in integration test by @KodrAus in https://github.com/emit-rs/emit/pull/103
* Tweak the term …

Prepare for 0.11.0-alpha.14 release

---

.github/workflows/batcher.yml
.github/workflows/core.yml
.github/workflows/emit.yml
.github/workflows/file.yml
.github/workflows/opentelemetry.yml
.github/workflows/otlp.yml
.github/workflows/term.yml
emitter/otlp/src/client/http.rs

There's been a gap in our CI testing where dev dependencies are triggering features that ensure crate builds work, but regular builds are failing.

Ensure we check no-test configurations in CI

---

.github/workflows/traceparent.yml
Cargo.toml
README.md
book/src/producing-events/tracing/propagating-across-services.md
book/src/producing-events/tracing/sampling.md
core/src/ctxt.rs
core/src/emitter.rs
core/src/filter.rs
emitter/opentelemetry/src/lib.rs
examples/common_patterns/Cargo.toml
examples/common_patterns/span_trace_filtering.rs
examples/common_patterns/span_trace_propagation.rs
examples/common_patterns/span_trace_sampling.rs
src/frame.rs
src/macro_hooks.rs
src/metric.rs
src/platform/thread_local_ctxt.rs
src/span.rs
test/ui/src/span.rs
traceparent/Cargo.toml
traceparent/README.md
traceparent/src/lib.rs

Closes #120
`emit` is only concerned with sampled context. This keeps its API simple and focused, but distributed apps still need to propagate the fact that a trace they're participating in is unsampled to any downstream callers, otherwise those will likely start a new trace.
This PR introduces a new subcrate `emit_traceparent` that can parse [W3C traceparent headers](https://www.w3.org/TR/trace-context). It also provides a central place to store and retrieve the active traceparent so you can use it for propagation and sampling. I've opted to add this in an external library instead of directly in `emit` to avoid making its own `emit::span` API murkier, and to avoid baking in competing concepts with the OpenTelemetry SDK, which, via `emit_opentelemetry`, is another backend option for apps …

Support parsing W3C traceparent headers with sampling

---

src/frame.rs

This is an advanced API for working with context frames. If you end up with a `Frame`, you may need to manage it in a way that doesn't cleanly map onto lifetime-scoped guards. The underlying `Ctxt` type allows this, so adding a method that unwraps the frame into its parts so you can manage them yourself is reasonable.

Allow splitting a Frame into its raw parts

---

macros/src/span.rs
src/macro_hooks.rs
test/ui/Cargo.toml
test/ui/src/span.rs

Closes #134 
One behavioral change in here is that `#[emit::span]` will now add the `Error` level to emitted spans if you don't otherwise set one. You can still use `err_lvl` to control it.

Support mapping the error value into a compatible type

---

src/macro_hooks.rs
src/span.rs
test/ui/src/span.rs

When using `#[emit::span]`, you may still want to control the span context. The natural way to do this is just adding them as properties to the `#[emit::span]` macro. Previously we'd prefer generated context over properties you pass in, but it makes more sense to prefer what the user provides so now this will produce a span that uses `ctxt` instead of generating one:
```rust
#[emit::span("work", trace_id: ctxt.trace_id(), span_parent: ctxt.span_parent(), span_id: ctxt.span_id())]
fn work(ctxt: SpanCtxt, ..) {
..
}
```

Ensure explicit trace/span ids take precedence in #[emit::span]

---

src/macro_hooks.rs
src/span.rs
test/ui/src/props.rs
test/ui/src/span.rs

Since trace and span ids can be represented as integers, we should be able to capture them in properties as integers too. This PR optimizes the conversion from raw values back into trace or span ids by trying to cast them to an integer before attempting to parse them from text.

Allow capturing trace and span ids as integers

---

book/src/emitting-events.md
src/setup.rs

Closes #122 
This PR introduces an `Init::flush_on_drop` method as an alternative to `blocking_flush` that will try flush when it goes out of scope:
```rust
fn main() {
let _guard = emit::setup().emit_to(..).init().flush_on_drop(Duration::from_secs(5));
..
}
```
It's important to bind this value to a proper identifier and not just `_`, otherwise it'll be dropped immediately.

Add a flush_on_drop guard to Init

---

book/src/SUMMARY.md
book/src/advanced-apps/non-main-setup.md
src/lib.rs
src/setup.rs

This PR introduces a `try_init` method to setup and a top-level `emit::blocking_flush()` function to help applications that don't initialize diagnostics in their `main` function.

Add docs and helpers for initializing outside main

---

examples/common_patterns/Cargo.toml
examples/common_patterns/testing.rs
macros/src/args.rs
macros/src/lib.rs
macros/src/span.rs
test/ui/src/span.rs

For #141 
This PR adds a new `setup` control parameter to `#[emit::span]` that can be used to invoke a function before running any `emit` code in the annotated function. It can be helpful for unit tests to reduce boilerplate when including diagnostics from them:
```rust
pub fn add(a: i32, b: i32) -> i32 {
let r = a + b;
emit::debug!("{r} = {a} + {b}");
r
}
#[cfg(test)]
fn setup() -> Option<impl Drop> {
emit::setup()
.emit_to(emit_term::stdout())
.try_init()
.map(|init| init.flush_on_drop(std::time::Duration::from_secs(1)))
}
#[test]
#[emit::span(setup, "add_1_1")]
fn add_1_1() {
assert_eq!(2, add(1, 1));
}
```

Add a setup control parameter to `#[emit::span]`

---

emitter/file/src/lib.rs
emitter/otlp/src/client.rs

Closes #143 
We do tear down the background thread when `emit_file` or `emit_otlp` types are dropped. This PR just adds some test cases to verify it.

Add tests for background teardown

---

examples/common_patterns/testing.rs
macros/src/args.rs
macros/src/emit.rs
macros/src/fmt.rs
macros/src/key.rs
macros/src/lib.rs
macros/src/span.rs
src/macro_hooks.rs
test/ui/src/span.rs

Closes #111
This PR cleans up the way we thread parameters around the internals of spans, and makes it possible to mark a span as failing if it panics. It might be good to be able to catch panics and attach them at some point in the future, but this PR doesn't go that far because catching panics, especially in async code, is not entirely trivial. I think this is only really useful for testing, generally Rust code shouldn't expect to panic, but in those cases getting the panic payload would be useful.

Add support for setting a panic level

---

src/level.rs

Closes #118 
This PR makes it possible to use the min level infrastructure with custom level types. It also makes the level parser more permissive so schemes like OTel’s `INFO3` will parse to `Level::Info`.

Make level infra more generic

---

src/frame.rs
src/metric.rs

Closes #119
This PR adds timestamp normalization support to `Reporter`. By default when the `std` feature is enabled, timestamps of sampled metrics will be normalized to a single value taken at the start of the call. Points will be assigned to this value and ranges will be shifted so the end is equal to it.

Support timestamp normalization on Reporter

---

core/src/filter.rs
core/src/runtime.rs

This type is useful to use when attempting to by-pass normal filtering, and is more obvious as `emit::filter::always()` than as `emit::Empty`:
```rust
emit::info!(when: emit::filter::always(), "..");
```

Re-instate filter::always

---

macros/src/lib.rs
macros/src/optional.rs
src/macro_hooks.rs
test/ui/src/props.rs

This PR allows using `#[emit::optional]` on values that are `Option<&T>` instead of just `Option<T>`. I haven't found a good way to handle the case of mapping `Option<T>` and `Option<&T>` in a non-consuming way without needing a hint in the attribute for it. We might be able to avoid it in the future.

Allow consuming Option<&T> instead of mapping as &Option<T>

---

examples/common_patterns/emit_optional_values.rs
macros/src/lib.rs
macros/src/optional.rs
src/macro_hooks.rs
test/ui/src/compile_fail/std/emit_props_optional_non_ref.rs
test/ui/src/compile_fail/std/emit_props_optional_non_ref.stderr
test/ui/src/props.rs

Followup to #151 
I found that the best approach to dealing with `&Option<T>` vs `Option<&T>` is just always require `Option<&T>`, because we can provide nicer compile errors, and calling `as_ref()` on options is a really common thing to do in Rust already.

Rework optional attribute to always require Option<&T>

---

emitter/otlp/src/data.rs
emitter/otlp/src/data/any_value.rs
emitter/otlp/src/data/logs.rs
emitter/otlp/src/data/logs/log_record.rs
emitter/otlp/src/data/resource.rs
emitter/otlp/src/data/traces.rs
emitter/otlp/src/data/traces/span.rs

Closes #158 
This PR writes the cause chain of an emitted error in the well-known `err` property into the `exception.stacktrace` attribute on the log record, or on the _exception_ span event in `emit_otlp`.
The value of the `exception.stacktrace` will include one line per cause, like:
```
caused by: there was a problem
caused by: IO error
```

Write error source chain to exception.stacktrace if present

---

emitter/otlp/src/data/logs.rs
macros/src/span.rs
test/ui/src/span.rs

Fix up binding name of err control param

---

book/src/producing-events/tracing/manual-span-completion.md
emitter/file/src/lib.rs
emitter/otlp/src/client.rs
emitter/otlp/src/lib.rs
examples/common_patterns/emit_debug_values.rs
examples/common_patterns/span_manual_completion.rs
examples/common_patterns/span_trace_propagation.rs
macros/src/span.rs
src/macro_hooks.rs
src/metric.rs
src/span.rs
test/ui/src/compile_fail/std/emit_props_non_display_interpolated.stderr
test/ui/src/compile_fail/std/emit_props_optional_non_ref.stderr
test/ui/src/compile_fail/std/span_guard_err.rs
test/ui/src/compile_fail/std/span_guard_err.stderr
test/ui/src/compile_fail/std/span_guard_err_lvl.rs
test/ui/src/compile_fail/std/span_guard_err_lvl.stderr
test/ui/src/compile_fail/std/span_guard_ok_lvl.rs
test/ui/src/compile_fail/std/span_guard_ok_lvl.stderr
test/ui/src/span.rs

Closes #166 
Closes #167 
This PR reworks the `SpanGuard` type to not rely on the props type `P` on its resulting span. This means we can change `P` while the span executes, such as by pushing properties to it, without needing to rewrite its completion function.
I've also made span completion take `&mut self`, so you can use guards and do manual completion as well as automatic result completion without them conflicting.

Rework span completion to support adding props

---

core/src/emitter.rs
core/src/event.rs
core/src/filter.rs
core/src/lib.rs
core/src/path.rs
macros/src/build.rs
src/kind.rs
src/level.rs
src/lib.rs
src/metric.rs
src/span.rs
traceparent/src/lib.rs

Methods like `Path::new_unchecked` look like they should be unsafe, but aren't. They don't check whether the input value is valid, but there's no memory safety invariants tied to this. It sets off needless red flags when reviewing code to see `_unchecked` so we should just avoid that suffix if there's no use of the `unsafe` keyword to review.

Rename safe _unchecked methods to _raw

---

book/src/producing-events/tracing/sampling.md
traceparent/src/lib.rs

Also fixes up an outdated note in the book.

Rename in_sampled_trace to in_sampled_trace_filter

---

book/src/producing-events/tracing/manual-span-creation.md
core/src/template.rs
examples/common_patterns/span_manual_creation.rs
macros/src/build.rs
macros/src/dbg.rs
macros/src/emit.rs
macros/src/format.rs
macros/src/key.rs
macros/src/lib.rs
macros/src/props.rs
macros/src/span.rs
macros/src/template.rs
src/lib.rs
src/macro_hooks.rs
src/metric.rs
src/span.rs
test/ui/src/event.rs
test/ui/src/props.rs
test/ui/src/tpl.rs

This PR fixes up a few papercuts around `tpl!()`, `props!()`, and `evt!()` where they couldn't produce values you could assign to temporaries. Now you can.

Expand macros to code supporting temporaries

---

book/src/producing-events/tracing/manual-span-creation.md
examples/common_patterns/span_manual_creation.rs
macros/src/lib.rs
macros/src/span.rs
test/ui/src/lib.rs
test/ui/src/start_span.rs

Closes #188 
This PR adds a `start_span!` macro that lets you lift a `#[span]` attribute into a `let` binding.
For example, this attribute:
```rust
#[emit::span(guard: span, "Running an example", i)]
fn example(i: i32) {
let r = i + 1;
if r == 4 {
span.complete_with(emit::span::completion::from_fn(|evt| {
emit::error!(evt, "Running an example failed with {r}");
}));
} else {
span.complete_with(emit::span::completion::from_fn(|evt| {
emit::info!(evt, "Running an example produced {r}");
}));
}
}
```
can also be written as:
```rust
fn example(i: i32) {
let (span, frame) = emit::start_span!("Running an example", i);
frame.call(move || {
let r = i + 1;
if r == 4 {
span.complete_with(emit::span::completion::from_fn(|evt| {
emit::error!(evt, "Running an example failed with {r}");
}));
} else { …
```

Add a start_span! macro for easy span creation

---

book/src/producing-events/tracing/manual-span-creation.md
examples/common_patterns/span_manual_creation.rs
macros/src/lib.rs
macros/src/span.rs
src/macro_hooks.rs
src/span.rs
test/ui/src/lib.rs
test/ui/src/new_span.rs

This PR tweaks the new `ActiveSpan` creation API to reduce the footgun of not passing ownership of the span into the frame. It does this by requiring a call to `ActiveSpan::start` to actually start the span, which can easily be done at the top of the `Frame::call` or `Frame::in_future` body.

Require ActiveSpans be manually started

---

examples/common_patterns/Cargo.toml

This is only used in examples. It looks like everything else is still current.

Bump thiserror to 2.0

---

batcher/src/lib.rs

The underlying calculation used for determining capacity was broken. Instead of using its rolling average value correctly, it would just assign and use the first slot indefinitely. I've fixed this up, added a little extra space to accommodate small shifts without needing to re-allocate, and slightly increased the rolling window size.

Fix up batcher capacity calculation

---

core/src/value.rs
emitter/term/src/lib.rs

Closes #210 
Rather than getting spongy with sequence semantics, I've opted to just return an optional vec instead. That way, if you want an empty one you can `unwrap_or_default()`, or if you want one with a single element you can `unwrap_or_else(|| vec![v.as_f64()])`.

Replace `Value::as_f64_seq` with `Value::to_f64_seq` with clearer semantics

---

Cargo.toml
emitter/file/Cargo.toml
src/platform.rs
src/setup.rs

This change makes it easier to configure `emit` in environments with `std`, but where `getrandom` is undesirable.

Improve support for building on wasm32-unknown-unknown

---

src/platform.rs
src/setup.rs

This PR just conveniently re-exports `DefaultEmitter` and `DefaultFilter` from the `emit::platform` module, since that's also where `DefaultClock` and `DefaultRng` are exported.

Re-export DefaultEmitter and DefaultFilter from emit::platform

---

book/src/SUMMARY.md
book/src/advanced-apps/web-assembly.md
book/src/producing-events/tracing/limitations.md
src/timer.rs

This PR adds a link to [`emit_web`](https://github.com/emit-rs/emit_web) in the guide. It also more strongly calls out the lack of guaranteed monotonicity in the tracing data model using a pair of timestamps.

Add a guide page on wasm and note lack of monotonicity of timers

---

core/src/value.rs
src/setup.rs
src/span.rs

This PR removes the APIs that have been deprecated since `0.11.0` before we stabilize `1.0.0` proper.

Remove deprecated APIs in preparation for 1.0.0

---

emitter/otlp/src/client/http.rs

This appears to cause OTLP emission to fail for HTTPS URIs when the port is unspecified.
A more complete implementation would reject schemes other than HTTP/HTTPS, let me know if you'd like that addition made.

Default port is 443 when URIs use HTTPS scheme

---

Cargo.toml
book/src/emitting-events/console.md
core/Cargo.toml
core/src/extent.rs
core/src/props.rs
core/src/template.rs
core/src/timestamp.rs
examples/common_patterns/Cargo.toml
examples/common_patterns/emit_json.rs
src/span.rs

Closes #233
Closes #126 
This PR implements `serde::Serialize` and `sval::Value` on more datatypes, and adds an `AsMap` adapter to `Props` that makes it easier to use in serialization code. Together, this makes it possible to write a custom serializer for events in any format using `serde` or `sval` that supports whatever conventions a specific use case may need without us needing to add a lot of configuration options to `emit_term` or `emit_file` for them.

Implement serialization traits for more types

---

.github/workflows/otlp.yml
emitter/otlp/Cargo.toml
emitter/otlp/src/client/http.rs
emitter/otlp/src/lib.rs
emitter/otlp/test/integration/Cargo.toml
emitter/otlp/test/integration/src/main.rs

I kind of knew this was coming, even though I wanted to avoid it. `rustls` has a very strict policy of feature support, which is admirable, but sometimes means you get stuck between a rock and a hard place trying to integrate with all manner of proxies and load balancers.
This PR adds support for using `native-tls` as the provider of TLS connections in `emit_otlp` by adding the `tls-native` Cargo feature. When enabled, it will take precedence over `rustls`.
Still TODO:

Add support for using the native TLS support on the platform

---

emitter/otlp/Cargo.toml

These dependencies are not intended to be public features.

Mark emit_otlp dependencies as private

---

core/src/value.rs
emitter/otlp/Cargo.toml
emitter/otlp/src/data/logs.rs
emitter/otlp/src/data/traces/span.rs

This PR tweaks the `Display` implementation of `Value` to include the top and bottom of the error cause chain when displaying them. This makes their output much more useful in situations where you're just rendering values with `.to_string()`.
Since Rust errors are typically an independent message fragment, we can usually combine multiple together with a separator without producing illogical output.
This only applies when formatting `Value`s containing errors using `Display`, it doesn't affect `Debug`.

Include the top and bottom of the error chain in Value display

---

emitter/file/Cargo.toml

Like #241, but for `emit_file`. I had a look through the rest of our `Cargo.toml`s and there don't seem to be any more cases of this accidental dependency leakage to fix.

Make file dependencies private

---

.github/workflows/batcher.yml
batcher/Cargo.toml
batcher/src/lib.rs
batcher/src/sync.rs
batcher/src/tokio.rs
batcher/src/web.rs
core/src/ctxt.rs
core/src/event.rs
core/src/props.rs
emitter/file/src/lib.rs
emitter/otlp/src/client.rs
emitter/otlp/src/data.rs
emitter/otlp/src/data/metrics.rs
src/platform/thread_local_ctxt.rs
test/ui/src/util.rs

Part of #243 
This PR makes `emit_batcher` work in `wasm32-unknown-unknown` when the `web` feature is enabled. It currently uses a fire-and-forget promise and timeouts based on `setTimeout` to run the batcher. There are a few features that aren't available, most notably `blocking_flush`. Since we're running on a single-threaded runtime, we can't block waiting for another task to complete.
Still TODO:

Support `emit_batcher` in web-based wasm projects

---

README.md
book/src/producing-events.md
book/src/producing-events/logging.md
book/src/producing-events/metrics.md
book/src/producing-events/tracing.md

This PR adds a few links to the macro syntax in a few places you might go looking for it as a new user.

Add links to the macro syntax

---

core/src/ctxt.rs
src/platform/thread_local_ctxt.rs

This PR applies a few optimizations to the `Ctxt` infrastructure to reduce the cost of contextual logging. The main changes are:
- Use the same approach as `erased-serde` to avoid needing to allocate for small frames by storing them inline in the value. I opted for the same 2-ptr size limit, which is enough to store a thread local frame, but not enough to bloat the size of the type too much.
- Avoid allocating some common value types in the thread local frame like trace and span ids.

Some optimizations to Ctxt

---

Cargo.toml
core/Cargo.toml
core/src/ctxt.rs

This PR pulls in `value-bag/inline-str` so small strings are stored inline instead of in `Box` or `Arc`.

Inline small strings when buffering values

---

book/src/producing-events/tracing/propagating-across-threads.md
src/frame.rs

This makes usage more similar to `in_future` when one wants to pass the current props to another thread.
The common case is for pusing the current frame into a spawned thread. The previous recommendation was this:
```rust
std::thread::spawn({
let ctxt = emit::Frame::current(emit::ctxt());
move || ctxt.call(|| { /* useful stuff */ })
});
```
which is a lot to take in with the 2 closures.
With this change, the same code becomes:
```rust
std::thread::spawn(emit::Frame::current(emit::ctxt()).in_fn(move || {/* useful stuff */}));
```
simplifying a common pattern and making it more similar to the async version.
The previous style is still necessary for anything that's not `FnOnce() -> T` (e.g.: any function that takes an argument), so I've left that style in the documentation as well.

feat: `in_fn` to simplify some call sites

---

.github/workflows/otlp.yml
Cargo.toml
emitter/otlp/test/throughput/src/main.rs

This PR just continues making the OTLP throughput test more useful for investigating performance issues by adding a few switches to control whether to spawn an `otelcol` child process, and whether to wait for it to flush.

Add some cmdline switches to otlp throughput harness

---

book/src/emitting-events.md
book/src/emitting-events/otlp.md
book/src/filtering-events.md
book/src/producing-events/tracing/manual-span-creation.md
src/setup.rs

This PR just cleans up some issues and typos I spotted in the docs.
I've also added a `Setup::into_runtime` method, because I keep finding myself wanting to create a standalone runtime, and the standard entrypoint to configuration is via `Setup`.

Clean up some docs issues

---

macros/src/span.rs
src/macro_hooks.rs

This PR replaces `emit::span::completion::from_fn` calls in `#[span]` macro expansion with concrete impls of `emit::span::Completion`s. This has been a todo for a while that I only haven't done because the ergonomics are much worse. It does have the benefit of avoiding a bit of dynamic dispatch, which for code a user never has to write is a nice benefit.
This shouldn't have any impact on how arguments in the `#[span]` macros are captured.

Replace from_fn calls in span macro expansion with explicit types

---

book/src/working-with-events.md

This PR just adds a note to the docs on how `Value` specializes its `Display` representation for errors.

Add note to book on value error formatting

---

core/src/timestamp.rs
core/src/well_known.rs
emitter/otlp/src/client/traces.rs
emitter/otlp/src/data.rs
emitter/otlp/src/data/logs/log_record.rs
emitter/otlp/src/data/metrics.rs
emitter/otlp/src/data/traces.rs
emitter/otlp/src/data/traces/span.rs
emitter/otlp/src/lib.rs
src/kind.rs
src/level.rs
src/span.rs

For #169 
This PR adds support for OpenTelemetry's span kinds to `emit_otlp`. It does this via a new well-known `span_kind` property, which other emitters may also opt-in to supporting if they want too.
The handling of span kinds in `emit_otlp` follows the same pattern as span names. If present, the `span_kind` property will inform the kind of the span, but can also be configured.

Support OpenTelemetry's span kinds in emit_otlp

---

core/src/runtime.rs
emitter/otlp/test/integration/src/main.rs

This PR just introduces an inherent `Runtime::blocking_flush` method, which just lets you flush a custom runtime without having to import the `Emitter` trait.

Add an inherent blocking_flush method to Runtime

---

core/src/props.rs
core/src/value.rs
src/macro_hooks.rs

This PR introduces a new `Props::size` method that acts as a size hint. We then use this method to optimize `Props::dedup` for small numbers of properties. In some quick testing, this ends up being roughly 30% faster deduplicating 16 unique 13 character keys. Performance for deduplicating larger sets is largely unchanged.
I've also added non-default impls for more `Props` methods.

Optimize Props::dedup

---

.github/workflows/emit.yml
batcher/Cargo.toml
batcher/src/sync.rs
src/platform.rs
src/setup.rs

This PR enhances `setup()` to warn through the internal runtime if the platform or Cargo configuration doesn't allow certain platform dependencies and no alternative is configured. `emit`'s docs all point you to configuring this internal runtime whenever you spot something unexpected in your diagnostic pipeline so it should help guide users to figuring out why timestamps may be missing, or why trace data may be missing span context.

Warn through the internal runtime if configuration is incomplete

---

core/src/event.rs
core/src/props.rs
core/src/str.rs
core/src/value.rs
emitter/otlp/src/client/http.rs
emitter/otlp/src/client/http/tokio.rs
emitter/otlp/src/client/http/web.rs
emitter/otlp/src/client/stub.rs
emitter/otlp/src/lib.rs
macros/src/format.rs
src/lib.rs

Part of #278 
This PR adds a `FromProps` trait and a `Props::collect` method that can be used to construct common collection types from a given `impl Props`. It aims to avoid the de-duplication footgun of manually constructing collections from `Props` and taking the last value for a key instead of the first.
I've opted to make this `FromProps` trait infallible instead of fallible or optional. That means the bounds used for values are `From<Value<'kv>>` instead of `FromValue`, and the trait returns `Self` instead of `Option<Self>`. That seemed like a better formulation than needing to figure out whether a failed conversion should be discarded, added to the collection as `None`, or cause the whole conversion to fail.
I've added a new `OwnedProps` type that collects any `P: Props` into an …

Add a FromProps trait for constructing collections from props

---

book/src/producing-events/metrics.md
book/src/producing-events/tracing.md

This PR just adds some more details to `emit`'s metrics model to note that it doesn't define instruments like counters or gauges for you. It's instead focused on how to represent samples taken from those types you define or pull in from elsewhere.

Note that emit's metrics model is for samples, not meters

---

macros/src/doc_new_span.md

Our docs for `new_span!` point to other types but it would be nice to have an inline example of how to use the span once you've created it.

Add an examaple to new_span showing how to enter it

---

emitter/otlp/src/data/metrics.rs
test/ui/src/compile_fail/std/emit_props_non_display_interpolated.stderr

This PR just sanity checks we map `emit`'s metric types to the right aggregation temporality in `emit_otlp`, and stops using the _histogram_ terminology to refer to timeseries metrics.

Add some tests for picking aggregation temporality

---

core/src/well_known.rs
emitter/otlp/src/data/metrics.rs
src/metric.rs
src/platform.rs
src/platform/libm.rs

For #303 
This PR adds the fundamental `emit::metric::bucket_midpoint` function that can be used to produce exponential histograms of input data. It also adds well-known properties for tacking exponential histograms onto other metric samples.
I've ended up interning the relevant parts of `libm` I needed to implement `bucket_midpoint` in a portable and `no_std` compatible way.

Support exponential histograms in `emit_core` and `emit`

---

book/src/producing-events/logging/levels.md
examples/common_patterns/Cargo.toml
examples/common_patterns/level_custom.rs

This PR just fills in more details about using custom levels in `emit`.

Update section on levels to include custom level example
