emit-rs/emit

src/lib.rs

Looks like Atom has messed with the formatting. All I've done is change `.unwrap()` on `env::var` to `.unwrap_or("User".to_string())`.

Make env::var tests pass on nix

---

src/enrichers/fixed_property/mod.rs

One more tiny step towards #12.

Remove static bound on FixedPropertyEnricher property name

---

README.md
src/collectors/mod.rs
src/collectors/seq/mod.rs
src/collectors/stdio/mod.rs
src/enrichers/fixed_property/mod.rs
src/formatters/json/mod.rs
src/formatters/mod.rs
src/formatters/raw/mod.rs
src/formatters/text/mod.rs
src/lib.rs
src/pipeline/async.rs
src/pipeline/builder.rs
src/pipeline/chain.rs
src/pipeline/reference.rs
src/templates/repl.rs
src/test_support.rs

Work-in-progress, but opening the PR in the hope of some early feedback :-)
The JSON format implemented is the one defined here: https://github.com/nblumhardt/serilog-formatting-compact#format-details

`TextFormatter` plus raw, JSON and plain text impls

---

.travis.yml

For #29 
I'm pretty sure this isn't actually going to test the doc upload... We might just have to mess around with it on master if it doesn't work :)

Add docs ci to travis

---

README.md
emitter/opentelemetry/src/lib.rs
emitter/otlp/src/lib.rs
src/lib.rs
src/setup.rs

This PR just updates a few links and ensures versions are all specified consistently.

Update some links and docs

---

Cargo.toml
README.md
batcher/Cargo.toml
batcher/README.md
core/Cargo.toml
emitter/file/Cargo.toml
emitter/file/README.md
emitter/file/src/lib.rs
emitter/opentelemetry/Cargo.toml
emitter/opentelemetry/README.md
emitter/opentelemetry/src/lib.rs
emitter/otlp/Cargo.toml
emitter/otlp/README.md
emitter/otlp/gen/Cargo.toml
emitter/otlp/src/lib.rs
emitter/term/Cargo.toml
emitter/term/README.md
emitter/term/src/lib.rs
examples/common_patterns/Cargo.toml
examples/opentelemetry/direct_otlp/Cargo.toml
examples/opentelemetry/via_sdk/Cargo.toml
macros/Cargo.toml
macros/README.md
src/lib.rs
src/setup.rs

* Default Template formatting to braced and rename event to evt by @KodrAus in https://github.com/emit-rs/emit/pull/54

Prepare for 0.11.0-alpha.5 release

---

emitter/file/src/lib.rs

Include event module in default file writer

---

src/macro_hooks.rs

This PR reworks the internal macro hook traits to let us provide more semantic error messages when required trait bounds aren't satisfied in the macros.

Use diagnostic::on_unimplemented to improve error messages from emit::as_* attributes

---

Cargo.toml
README.md
batcher/Cargo.toml
batcher/README.md
core/Cargo.toml
emitter/file/Cargo.toml
emitter/file/README.md
emitter/file/src/lib.rs
emitter/opentelemetry/Cargo.toml
emitter/opentelemetry/README.md
emitter/opentelemetry/src/lib.rs
emitter/otlp/Cargo.toml
emitter/otlp/README.md
emitter/otlp/src/lib.rs
emitter/term/Cargo.toml
emitter/term/README.md
emitter/term/src/lib.rs
examples/common_patterns/Cargo.toml
examples/opentelemetry/direct_otlp/Cargo.toml
examples/opentelemetry/via_sdk/Cargo.toml
macros/Cargo.toml
macros/README.md
src/lib.rs
src/setup.rs

* Add async variants of blocking tokio functions by @KodrAus in https://github.com/emit-rs/emit/pull/82

Prepare for 0.11.0-alpha.11 release

---

macros/src/span.rs
test/ui/src/span.rs

Fix up explicit return breaking ok_lvl and err_lvl in sync spans

---

batcher/src/sync.rs

Fix up flaky batcher test

---

core/src/rng.rs
core/src/timestamp.rs
emitter/file/src/lib.rs
emitter/otlp/gen/main.rs
emitter/term/src/lib.rs

This PR adds some basic tests for `emit_term` and fills in a few more for `emit_file`.

Add some tests for emit_term

---

README.md
batcher/src/lib.rs
batcher/src/sync.rs
batcher/src/tokio.rs
emitter/file/src/internal_metrics.rs
emitter/file/src/lib.rs
emitter/opentelemetry/src/lib.rs
emitter/otlp/src/client.rs
emitter/otlp/src/internal_metrics.rs

This PR just cleans up some loose ends around the codebase to get it in shape for another release.

Some docs and cleanups

---

Cargo.toml
README.md
batcher/Cargo.toml
batcher/README.md
core/Cargo.toml
emitter/file/Cargo.toml
emitter/file/README.md
emitter/file/src/lib.rs
emitter/opentelemetry/Cargo.toml
emitter/opentelemetry/README.md
emitter/opentelemetry/src/lib.rs
emitter/otlp/Cargo.toml
emitter/otlp/README.md
emitter/otlp/src/lib.rs
emitter/term/Cargo.toml
emitter/term/README.md
emitter/term/src/lib.rs
examples/common_patterns/Cargo.toml
examples/opentelemetry/direct_otlp/Cargo.toml
examples/opentelemetry/via_sdk/Cargo.toml
macros/Cargo.toml
macros/README.md
src/lib.rs
src/setup.rs

* Ensure we check no-test configurations in CI by @KodrAus in https://github.com/emit-rs/emit/pull/106

Prepare for 0.11.0-alpha.15 release

---

macros/src/span.rs
test/ui/Cargo.toml
test/ui/src/compile_fail/std/span_ok_lvl_impl_trait_return.rs
test/ui/src/compile_fail/std/span_ok_lvl_impl_trait_return.stderr
test/ui/src/lib.rs
test/ui/src/span.rs

Fix up impl trait as inferred type

---

Cargo.toml
README.md
batcher/Cargo.toml
batcher/README.md
core/Cargo.toml
emitter/file/Cargo.toml
emitter/file/README.md
emitter/file/src/lib.rs
emitter/opentelemetry/Cargo.toml
emitter/opentelemetry/README.md
emitter/opentelemetry/src/lib.rs
emitter/otlp/Cargo.toml
emitter/otlp/README.md
emitter/otlp/src/lib.rs
emitter/term/Cargo.toml
emitter/term/README.md
emitter/term/src/lib.rs
examples/common_patterns/Cargo.toml
examples/opentelemetry/direct_otlp/Cargo.toml
examples/opentelemetry/via_sdk/Cargo.toml
macros/Cargo.toml
macros/README.md
src/lib.rs
src/setup.rs

* Update to opentelemetry 0.25 by @KodrAus in https://github.com/emit-rs/emit/pull/108
* Fix up impl trait as inferred type by @KodrAus in https://github.com/emit-rs/emit/pull/110

Prepare for 0.11.0-alpha.16 release

---

Cargo.toml
README.md
batcher/Cargo.toml
batcher/README.md
book/src/about.md
book/src/getting-started.md
core/Cargo.toml
emitter/file/Cargo.toml
emitter/file/README.md
emitter/file/src/lib.rs
emitter/opentelemetry/Cargo.toml
emitter/opentelemetry/README.md
emitter/opentelemetry/src/lib.rs
emitter/otlp/Cargo.toml
emitter/otlp/README.md
emitter/otlp/src/lib.rs
emitter/term/Cargo.toml
emitter/term/README.md
emitter/term/src/lib.rs
examples/common_patterns/Cargo.toml
examples/opentelemetry/direct_otlp/Cargo.toml
examples/opentelemetry/via_sdk/Cargo.toml
macros/Cargo.toml
macros/README.md
src/lib.rs
src/setup.rs

* Docs cleanup by @KodrAus in https://github.com/emit-rs/emit/pull/113

Prepare for 0.11.0-alpha.17 release

---

book/src/producing-events/tracing/propagating-across-services.md
book/src/producing-events/tracing/sampling.md
macros/src/span.rs
src/macro_hooks.rs
test/ui/src/compile_fail/std/emit_props_non_display_interpolated.stderr
test/ui/src/compile_fail/std/span_ok_lvl_impl_trait_return.rs
test/ui/src/compile_fail/std/span_ok_lvl_impl_trait_return.stderr
test/ui/src/span.rs

Remove need for type inference in spans with levels

---

book/src/producing-events/tracing/fallible-functions.md
examples/common_patterns/Cargo.toml
examples/common_patterns/span_fallible_anyhow.rs
macros/src/lib.rs

Follow-up to #135 that adds some examples and docs for the new feature.

Add docs and examples for the err control param

---

core/src/filter.rs

Remove unused imports

---

book/src/SUMMARY.md
book/src/working-with-events.md
core/src/str.rs
core/src/value.rs
examples/common_patterns/Cargo.toml
examples/common_patterns/filter_by_property.rs

Document working with event properties

---

README.md
book/src/producing-events/tracing/manual-span-completion.md

It bothers me every time I visit the readme...

Fix a typo in the readme

---

book/src/producing-events/logging/errors.md
book/src/producing-events/tracing/fallible-functions.md
examples/common_patterns/Cargo.toml
examples/common_patterns/emit_errors.rs
examples/common_patterns/emit_errors_anyhow.rs
examples/common_patterns/span_fallible_anyhow.rs
src/err.rs
src/lib.rs
src/span.rs
test/ui/src/props.rs
test/ui/src/span.rs

Add an err::as_ref function to help capture anyhow::Error

---

traceparent/src/lib.rs

Include other events in unsampled traces

---

traceparent/src/lib.rs

Support tracestate in emit_traceparent

---

book/src/producing-events/tracing/manual-span-completion.md
book/src/producing-events/tracing/manual-span-creation.md
book/src/producing-events/tracing/propagating-across-services.md
examples/common_patterns/Cargo.toml
examples/common_patterns/span_manual_creation.rs
examples/common_patterns/span_manual_creation_full.rs
examples/common_patterns/span_trace_propagation.rs
examples/common_patterns/span_trace_sampling.rs
src/setup.rs
traceparent/src/lib.rs

This PR just continues to flesh out and fill in more docs for creating and completing traces

Work on more tracing docs

---

book/src/advanced-apps/integrating-with-open-telemetry.md
book/src/producing-events/tracing/propagating-across-services.md
book/src/producing-events/tracing/sampling.md
book/src/reference/architecture.md
core/src/event.rs
emitter/otlp/src/lib.rs
examples/common_patterns/Cargo.toml
examples/common_patterns/span.rs
examples/common_patterns/span_trace_propagation.rs
src/lib.rs

This PR is just a follow-up to `0.11.0` that fixes up a few issues spotted in the docs.

Fix up some docs issues

---

book/src/reference/architecture.md

This PR adds a diagram to the docs explaining the various types involved in producing and emitting spans.

Add a mermaid diagram for span lifecycle

---

book/src/producing-events/tracing/manual-span-completion.md
book/src/producing-events/tracing/manual-span-creation.md
book/src/reference/architecture.md
examples/common_patterns/span_manual_creation.rs
examples/common_patterns/span_manual_creation_full.rs
macros/src/lib.rs
src/macro_hooks.rs
src/span.rs
test/ui/src/span.rs

In the end, I think `SpanGuard` was a much better name, so am moving back to it now before letting it linger too long.

Prefer SpanGuard over ActiveSpan

---

book/src/producing-events/metrics/reporting-sources.md
book/src/producing-events/tracing/fallible-functions.md
macros/src/lib.rs

This PR is just another collection of doc fixups and clarifications.

Fix up some more nitpicks in the docs

---

README.md

This PR just tweaks our readme example a bit to call out notable features and separate user code from boilerplate.

Tweak the readme example a bit

---

batcher/src/lib.rs
core/src/value.rs
emitter/otlp/src/client.rs
emitter/otlp/src/client/http.rs
emitter/otlp/src/data.rs
emitter/otlp/src/internal_metrics.rs

Add timeout to OTLP batches and split by request size

---

emitter/term/src/lib.rs

This PR adds support for writing events to `stderr` using `emit_term`. The format is the same as `stdout` uses, and the configuration options are the same.

Support emitting console events to stderr

---

README.md
book/src/advanced-apps/embedded.md
book/src/advanced-apps/integrating-with-open-telemetry.md

This PR just continues improving docs

Fill in some more docs

---

emitter/otlp/src/data.rs

This PR shares allocations and pre-allocates capacity for protobuf encoded messages to avoid needing to re-allocate as frequently while encoding them. The scale of the improvement largely depends on the size and shape of the incoming data. More complex messages benefit more, because their size is largely unknown upfront.

Pre-allocate buffers for protobuf encoding

---

emitter/otlp/test/throughput/src/main.rs

This PR just adds tracing to the OTLP throughput harness so it gives us some idea of where time is being spent in `#[emit::span]` and trace encoding.

Also exercise tracing in OTLP throughput

---

macros/src/doc_dbg.md
macros/src/doc_emit.md
macros/src/doc_evt.md
macros/src/doc_fmt.md
macros/src/doc_new_span.md
macros/src/doc_span.md
macros/src/doc_tpl.md
macros/src/lib.rs

Closes #269 
This PR improves the API docs for macros with more details on syntax and examples.

Improve API docs for macros

---

src/platform/thread_local_ctxt.rs

This is one of the motivations for #278.
The current implementation of `ThreadLocalCtxt::open_push` is incorrect if the set of properties to push contains duplicates. Instead of taking the first key for a given value, it takes the last. To fix it, I've added a generation field that's updated once for each set of properties we push. That way we know whether we're attempting to overwrite a property added by a previous set, or whether we're attempting to overwrite one we just added.

Fix up deduplication of thread local ctxt props

---

book/src/advanced-apps/web-assembly.md

This PR just cleans and tightens up the WebAssembly docs in the book a bit.

Tweak wasm docs a bit

---

book/src/producing-events/metrics.md
book/src/reference/events.md
test/ui/src/compile_fail/std/span_guard_err.rs
test/ui/src/compile_fail/std/span_guard_err.stderr
test/ui/src/compile_fail/std/span_guard_err_lvl.rs
test/ui/src/compile_fail/std/span_guard_err_lvl.stderr
test/ui/src/compile_fail/std/span_guard_ok_lvl.rs
test/ui/src/compile_fail/std/span_guard_ok_lvl.stderr

This PR just does a quick pass over some docs and extends/fixes small issues in them.

Expand extension docs a bit
